# Generated by Xplorer, do not modify.
# This Makefile builds _single_build Debug

%:: RCS/%,v
%:: RCS/%
%:: s.%
%:: SCCS/s.%
.SUFFIXES:
.SUFFIXES: .a .o .c .cc .C .cpp .s .S .h


# There should not be an 'sh.exe' in path
export SHELL = cmd


# There should never be any unknown unix-like tools on the path
# In particular there should not be an 'sh.exe' in the system32 directory
export PATH = D:\usr\xtensa\XtDevTools\install\tools\RI-2021.8-win32\XtensaTools\bin\;D:\usr\xtensa\XtDevTools\install\tools\RI-2021.8-win32\XtensaTools\lib\iss\;C:\Windows\system32

all:
	cmd /c "cd /D ""D:\\usr\\xtensa\\Xplorer-9.0.18-workspaces\\EastTech_workspace\\optek_g4_sdk_a20_meiqi1008_add_sona\\bin\\optek_hvf4\\Debug"" && $(MAKE) all  "

clean:
	cmd /c "cd /D ""D:\\usr\\xtensa\\Xplorer-9.0.18-workspaces\\EastTech_workspace\\optek_g4_sdk_a20_meiqi1008_add_sona\\bin\\optek_hvf4\\Debug"" && $(MAKE) clean  "
