Rem @pause

Rem uart_boot_loader_bin_combination uart_boot_loader_baud_rate_detect.bin uart_boot_loader_header.bin firmare_for_erasing.bin BOOT_LOADER_FLAG:1 SFLASH_BIT_SIZE:8M uart_boot_loader_erasing_sFlash.bin

uart_boot_loader_bin_combination firmare_for_erasing.bin BOOT_LOADER_FLAG:1 SFLASH_BIT_SIZE:8M uart_boot_loader_erasing_sFlash.bin

@pause